# golangci-lint configuration file
# see: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  allow-parallel-runners: true

issues:
  max-same-issues: 0

linters:
  default: none

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/kubeflow/trainer/v2) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports.
