# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# KubeLinter configuration file
# For more information, see https://docs.kubelinter.io/#/configuring-kubelinter

# checks section configures which checks to run.
checks:
  # Do not include any of the default checks.
  # If this is false, all default checks are included,
  # and the "include" and "exclude" lists are applied on top of them.
  doNotIncludeBuiltIn: false

  # include is a list of check names to include.
  # include:
  #   - "check-name-1"

  # exclude is a list of check names to exclude.
  exclude:
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "mismatching-selector"
    - "no-read-only-root-fs"
    - "run-as-non-root"
    - "no-anti-affinity"
    - "non-existent-service-account" # Often false positive in kustomize
    - "latest-tag"
