// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RuntimePatchApplyConfiguration represents a declarative configuration of the RuntimePatch type for use
// with apply.
type RuntimePatchApplyConfiguration struct {
	Manager             *string                                     `json:"manager,omitempty"`
	Time                *v1.Time                                    `json:"time,omitempty"`
	TrainingRuntimeSpec *TrainingRuntimeSpecPatchApplyConfiguration `json:"trainingRuntimeSpec,omitempty"`
}

// RuntimePatchApplyConfiguration constructs a declarative configuration of the RuntimePatch type for use with
// apply.
func RuntimePatch() *RuntimePatchApplyConfiguration {
	return &RuntimePatchApplyConfiguration{}
}

// WithManager sets the Manager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manager field is set to the value of the last call.
func (b *RuntimePatchApplyConfiguration) WithManager(value string) *RuntimePatchApplyConfiguration {
	b.Manager = &value
	return b
}

// WithTime sets the Time field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Time field is set to the value of the last call.
func (b *RuntimePatchApplyConfiguration) WithTime(value v1.Time) *RuntimePatchApplyConfiguration {
	b.Time = &value
	return b
}

// WithTrainingRuntimeSpec sets the TrainingRuntimeSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrainingRuntimeSpec field is set to the value of the last call.
func (b *RuntimePatchApplyConfiguration) WithTrainingRuntimeSpec(value *TrainingRuntimeSpecPatchApplyConfiguration) *RuntimePatchApplyConfiguration {
	b.TrainingRuntimeSpec = value
	return b
}
