# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This was developed on AWS g4dn.xlarge, Tesla T4 GPUs
# eksctl create cluster --config-file ./eks-config-gpu.yaml
# eksctl delete cluster --config-file ./eks-config-gpu.yaml  --wait
# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig
# metadata:
#   name: gpu-cluster
#   region: us-east-2

# nodeGroups:
#   - name: hpsf-gpu-workers
#     instanceType: g4dn.xlarge
#     minSize: 2
#     maxSize: 2
#     desiredCapacity: 2
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: lammps-flux
spec:
  # Reference the pre-defined runtime by name
  runtimeRef:
    name: flux-distributed
  trainer:
    numNodes: 2
    numProcPerNode: 1
    image: ghcr.io/flux-framework/tutorials:gpu-lammps-hwloc
    # You do not need to write "flux run, etc" here. It will be wrapped
    command: [lmp_gpu, -k, "on", g, "8", "-sf", "kk", "-pk", "kokkos", "cuda/aware", "off", "newton", "on", neigh, half, -in, in.reaxff.hns, -v, "x", "8", -v, "y", "8", -v, z, "16", "-in", in.reaxff.hns, "-nocite"]
    resourcesPerNode:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    env:
     - name: OMPI_MCA_btl
       value: tcp,self
      # This is how we match the view (operating system and version) of the initContainer to install Flux
     - name: FLUX_VIEW_IMAGE
       value: ghcr.io/converged-computing/flux-view-ubuntu:tag-jammy
