# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Welcome New Contributors

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: |
            🎉 **Welcome to the Kubeflow Trainer!** 🎉

            Thanks for opening your first issue! We're happy to have you as part of our community 🚀

            **Here's what happens next:**

            - Our team will review your issue soon! cc @kubeflow/kubeflow-trainer-team
            - If you'd like to contribute to this issue, check out our [Contributing Guide](https://github.com/kubeflow/trainer/blob/master/CONTRIBUTING.md) for repo-specific guidelines and the [Kubeflow Contributor Guide](https://www.kubeflow.org/docs/about/contributing/) for general community standards.

            **Join the community:**
            - **Slack**: Join our [#kubeflow-trainer](https://www.kubeflow.org/docs/about/community/#kubeflow-slack-channels) Slack channel.
            - **Meetings**: Attend the [Kubeflow AutoML and Training Working Group](https://bit.ly/2PWVCkV) bi-weekly meetings.

            Feel free to ask questions in the comments if you need any help or clarification!
            Thanks again for contributing to Kubeflow! 🙏

          pr_message: |
            🎉 **Welcome to the Kubeflow Trainer!** 🎉

            Thanks for opening your first PR! We're happy to have you as part of our community 🚀

            **Here's what happens next:**

            - If you haven't already, please check out our [Contributing Guide](https://github.com/kubeflow/trainer/blob/master/CONTRIBUTING.md) for repo-specific guidelines and the [Kubeflow Contributor Guide](https://www.kubeflow.org/docs/about/contributing/) for general community standards.
            - Our team will review your PR soon! cc @kubeflow/kubeflow-trainer-team

            **Join the community:**
            - **Slack**: Join our [#kubeflow-trainer](https://www.kubeflow.org/docs/about/community/#kubeflow-slack-channels) Slack channel.
            - **Meetings**: Attend the [Kubeflow AutoML and Training Working Group](https://bit.ly/2PWVCkV) bi-weekly meetings.

            Feel free to ask questions in the comments if you need any help or clarification!
            Thanks again for contributing to Kubeflow! 🙏
